version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.2.7-node
    steps:
      - checkout
      - php/install-packages
      - run:
          name: "Run tests"
          command: |
            sudo pecl install pcov
            ./vendor/bin/phpunit --coverage-clover build/coverage-report/coverage.xml
workflows:
  build-and-test:
    jobs:
      - test-php
