services:
  Sulu\Bundle\DynamicFormAjaxValidation\Controller\ValidationController:
    class: Sulu\Bundle\DynamicFormAjaxValidation\Controller\ValidationController
    public: true
    arguments:
      $formBuilder: '@sulu_form.builder'
      $errorMessageTransformer: '@Sulu\Bundle\DynamicFormAjaxValidation\Form\Validation\ErrorMessageTransformer'

  Sulu\Bundle\DynamicFormAjaxValidation\Form\Validation\ErrorMessageTransformer:
    class: Sulu\Bundle\DynamicFormAjaxValidation\Form\Validation\ErrorMessageTransformer

  Sulu\Bundle\FormBundle\Event\RequestListener:
    alias: sulu_form.request_listener